{
  "assignments": [
    {
      "id": 1,
      "type": "concept",
      "correct_answer": "2",
      "hint": "exception은 영어로 '예외'라는 뜻이며, 일반적인 흐름을 벗어나는 상황을 가리킵니다."
    },
    {
      "id": 2,
      "type": "theory_concept",
      "correct_answer": "1",
      "hint": "'try' 블록 안의 코드가 정상적으로 실행되면 'except' 블록은 무시됩니다."
    },
    {
      "id": 3,
      "type": "metaphor",
      "correct_answer": "2",
      "hint": "'Exceptions'는 프로그램이 예상치 못한 상황에 직면했을 때, 그 상황을 처리하는 방법을 말합니다. 예를 들어, 프로그램이 정상적으로 동작하는 중에 어떤 이유로 인해 문제가 발생하면, 프로그램은 '예외'를 발생시키고 이를 처리하는 방법을 찾아야 합니다."
    },
    {
      "id": 4,
      "type": "implementation_basic",
      "test_cases": [
        {
          "input": "2",
          "output": "4"
        },
        {
          "input": "abc",
          "output": "잘못된 입력입니다."
        },
        {
          "input": "10",
          "output": "100"
        },
        {
          "input": "#$%",
          "output": "잘못된 입력입니다."
        }
      ],
      "hint": "try, except를 사용하여 예외 처리를 합니다. 입력받은 값을 int로 변환하여 제곱하되, ValueError가 발생하면 '잘못된 입력입니다.'를 출력합니다."
    },
    {
      "id": 5,
      "type": "implementation_basic",
      "test_cases": [
        {
          "input": "10, 2",
          "output": "5"
        },
        {
          "input": "10, 0",
          "output": "0으로 나눌 수 없습니다."
        }
      ],
      "hint": "먼저 사용자로부터 두 개의 숫자를 입력 받습니다. 그 다음, 두 번째 숫자가 0인지 확인합니다. 만약 0이라면 오류 메시지를 출력하고, 아니라면 첫 번째 숫자를 두 번째 숫자로 나눈 값을 출력합니다."
    }
  ],
  "metadata": {
    "version": 1,
    "created_at": "2025-01-24T12:49:16.930769"
  }
}